server:
    port: 8888
spring:
    profiles:
        active: test
    jpa:
        show-sql: true
    weixin:
        appId: wx25162193c94710fb
        appSecret: e196d72788a5374654736d941730ca3d
        encodingAESKey: Z8WAPsLJR9b46e92yFPwJFny6pc79TSsPIfwrUZlhuu
        tokenKey: bogle
    redis:
        database: 1
        hostName: localhost
        timeout: 6000
        port: 6379
    jedisPool:
        testOnBorrow: true
        testOnReturn: false
        testWhileIdle: true
        testOnCreate: true
